### PR TITLE
Support arrow keys for vscroll

### PR DESCRIPTION
**Pull request by bryevdv**
This PR adds support for using the up/down arrow keys to scroll the viewport (and shift + arrow keys for "fine" scroll).

The current values for `row_scroll_delta` were chosen fairly arbitrarily, any input re: actual user preferences is welcome. 

fixes: #33 

cc @elliottslaughter @lightsighter

### CODE REVIEW

**Comment by lightsighter** [comment]
I'll defer to Elliott on the code. Happy to have scrolling in all directions. 😁

**Comment by elliottslaughter** [comment]
When we have multiple windows, what's the expected behavior? Right now it appears to only vertically scroll the first window.

**Comment by bryevdv** [comment]
> When we have multiple windows, what's the expected behavior? Right now it appears to only vertically scroll the first window.

I'm not actually sure how to run the profiler with multiple windows, are there instructions/docs somewhere?

**Comment by elliottslaughter** [comment]
If you use the `--serve` mode, you can create two (or more) servers and then use `--attach` with two URLs. See:

https://legion.stanford.edu/profiling/#remotely-viewing-profiles-serve-and-attach-modes

**Comment by bryevdv** [comment]
> When we have multiple windows, what's the expected behavior? Right now it appears to only vertically scroll the first window.

I tested this with `--attach` and currently the vertical scroll affects each window independently (each window can be vertically scrolled, and vertically scrolling a window does not affect any other windows). 

Without knowing anything else, this is the behavior I would assume is correct. These are intended to be independent views of the same underlying data, correct? There is no guarantee the windows are even the same shape or size, and, AFAIK even in a "shared google doc" type scenario, my scrolling a window does not scroll other user's windows.

**Comment by elliottslaughter** [comment]
Ok, I tried this out and it does work. I'm confused, but I guess there's some magic in egui that tracks the cursor position and sends the scroll event to the right place.

**Pull request merged**
